FlowerPower/Models/CartViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FlowerPower.Models
{
    public class CartViewModel
    {
        public static List<Product> shoppingCartList = new List<Product>();

        public static string savedUserID = "";
    }
}

FlowerPower/Models/CartViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FlowerPower.Models
{
    public class CartViewModels
    {

    }
}

FlowerPower/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using FlowerPower.Models;

namespace FlowerPower.Controllers
{
    public class CartController : Controller
    {
        DB_A3D6D6_FlowerPowerJordyEntities db = new DB_A3D6D6_FlowerPowerJordyEntities();

        private List<Product> shoppingCartList = CartViewModel.shoppingCartList;

        // GET: Cart
        public ActionResult Index()
        {
            shoppingCartList.OrderByDescending(s => s.productPrice);

            return View(shoppingCartList);
        }

        [HttpPost]
        public ActionResult AddToCart(int productID)
        {
            Product p = db.Product.Where(m => m.productID == productID).First();

            if(!CartViewModel.shoppingCartList.Contains(p)) //if product is not in list, add it
            {
                CartViewModel.shoppingCartList.Add(p);
            }

            return PartialView("CartPartial", CartViewModel.shoppingCartList);
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int productID)
        {
            List<Product> products = CartViewModel.shoppingCartList.Where(m => m.productID == productID).ToList();

            foreach (Product product in products)
            {
                if (product.productID == productID)
                {
                    CartViewModel.shoppingCartList.Remove(product);
                    break;
                }
            }

            return PartialView("CartPartial", CartViewModel.shoppingCartList);
        }

        [HttpPost]
        public ActionResult RemoveAllFromCart(int productID)
        {
            List<Product> products = CartViewModel.shoppingCartList.Where(m => m.productID == productID).ToList();

            foreach(Product product in products)
            {
                if(product.productID == productID)
                {
                    CartViewModel.shoppingCartList.Remove(product);
                }
            }

            return PartialView("CartPartial", CartViewModel.shoppingCartList);
        }

        [HttpPost]
        public ActionResult ShowCart()
        {

            return PartialView("CartPartial", CartViewModel.shoppingCartList);
        }
    }
}

FlowerPower/Views/Cart/CartPartial.cshtml
@model IEnumerable<FlowerPower.Models.Product>

@{
    bool[] inList = new bool[999];
    int[] productQuantity = new int[999];
    int[] productID = new int[999];
    string[] productName = new string[999];
    int i = 0;
}

@if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Medewerker"))
{
    <script>
        $(document).ready(function () {
            $("#cart").css("display", "none");
        });
    </script>
}

<i class="fas fa-times-circle menubtn"></i>

<div class="cartcontainer">

    <div class="carter">
        <i class="fas fa-shopping-cart"></i>
    </div>
</div>
@foreach (var item in Model)
{
    if (!inList[item.productID])
    {
        inList[item.productID] = true;
        productQuantity[item.productID] = 1;
        productID[i] = item.productID;
        productName[item.productID] = item.productName;
    }
    else
    {
        productQuantity[item.productID]++;
    }
    i++;
}

<div class="row" style="padding-top: 15px;border-top:1px solid black;">
    @foreach (var item in productID)
    {
        if (item == 0)
        {
            continue;
        }

        <div class="col-md-4">
            @Html.DisplayFor(m => productName[item])
        </div>
        <div class="col-md-6">
            <button type="button" class="btn btn-warning btn-sm btnMinus" data-assigned-id="@item" onclick="RemoveFromCartButton(this)">
                <i class="fas fa-minus" aria-hidden="true"></i>
            </button>
            @Html.DisplayFor(m => productQuantity[item])
            <button type="button" class="btn btn-success btn-sm btnAdd" data-assigned-id="@item" onclick="AddOneToCartButton(this)">
                <i class="fas fa-plus" aria-hidden="true"></i>
            </button>
        </div>
        <div class="col-md-2" style="padding: 0px !important;">
            <button type="button" class="btn btn-danger btn-sm btnRemove" data-assigned-id="@item" onclick="RemoveAllFromCartButton(this)">
                <i class="fas fa-trash" aria-hidden="true"></i>
            </button>
        </div>
        <br /><br />
    }
</div>

<div class="ordercontainer">
    <button id="confirmationBtn" type="submit" class="btn btn-success orderBtn">
        <i class="fas fa-plus">Bevestigen</i>
    </button>
</div>

<script>
    $(document).ready(function () {
        var menu = 0;
        $('.menubtn').on('click', function () {
            switch (menu) {
                case 0:
                    $('.body-content .container').css("margin", "0 10%");
                    $('#cart').animate({
                        width: '0',
                        padding: '0'
                    }, 300);
                    $('#cart .row').css("margin-left", "0");
                    $('#cart .row').css("margin-right", "0");
                    $('#cart').css("min-width", "0");
                    menu = 1;
                    break;
                case 1:
                    $('.body-content .container').css("margin", "0");
                    $('#cart').css("min-width", "250px");
                    $('#cart').animate({
                        width: '20%',
                        padding: '20px'
                    }, 200);
                    $('#cart .row').css("margin-left", "-15px");
                    $('#cart .row').css("margin-right", "-15px");
                    menu = 0;
                    break;

            }

        })
    })

    /**
     *
     * Add 1 to cart
     *
     */



    function AddOneToCartButton(elem) {
        AddOneToCart(parseInt($(elem).data('assigned-id')));
    }

    function AddOneToCart(id) {
        $.ajax({
            url: "@Url.Action("AddToCart", "Cart")",
            data: {
                productID: id
            },
            method: "POST",
            success: function (data) {
                $("#cart").html(data);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                if (xhr.status == 404) {
                    return;
                }
            }
        });
    }

        $("#confirmationBtn").click(function () {
            window.location.href = "@Url.Action("Index", "Confirmation")";
        });

    /**
     *
     * Remove 1 from cart
     *
     */

    function RemoveFromCartButton(elem) {
        RemoveFromCart(parseInt($(elem).data('assigned-id')));
    }

    function RemoveFromCart(id) {
        $.ajax({
            url: "@Url.Action("RemoveFromCart", "Cart")",
            data: {
                productID: id
            },
            method: "POST",
            success: function (data) {
                $("#cart").html(data);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                if (xhr.status == 404) {
                    return;
                }
            }
        });
    }

    /**
     *
     * Remove all from cart
     *
     */

    function RemoveAllFromCartButton(elem) {
        RemoveAllFromCart(parseInt($(elem).data('assigned-id')));
    }

    function RemoveAllFromCart(id) {
        $.ajax({
            url: "@Url.Action("RemoveAllFromCart", "Cart")",
            data: {
                productID: id
            },
            method: "POST",
            success: function (data) {
                $("#cart").html(data);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                if (xhr.status == 404) {
                    return;
                }
            }
        });
    }
</script>

FlowerPower/Views/Cart/Index.cshtml
@model IEnumerable<FlowerPower.Models.Product>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@foreach (var item in Model)
{
    @Html.DisplayFor(m => item.productName)
}