FlowerPower/Controllers/ConfirmationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FlowerPower.Models;
using Microsoft.AspNet.Identity;

namespace FlowerPower.Controllers
{
    public class ConfirmationController : Controller
    {

        DB_A3D6D6_FlowerPowerJordyEntities db = new DB_A3D6D6_FlowerPowerJordyEntities();

        // GET: Confirmation
        public ActionResult Index()
        {
            return View(CartViewModel.shoppingCartList);
        }

        [Authorize(Roles = "Admin,Klant,Medewerker")]
        public ActionResult ChooseStore()
        {
            IEnumerable<Store> stores = db.Store;
            SelectList storeList = new SelectList(stores, "storeID", "address");

            storeList.OrderBy(l => l.Value);

            ViewBag.Stores = storeList;

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Klant,Medewerker")]
        public ActionResult GetOrderButton(int? storeID)
        {
            if (storeID == null)
            {
                return new HttpNotFoundResult();
            }

            return PartialView("GetOrderButtonPartial");
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Klant,Medewerker")]
        public ActionResult OnClickStoreButton(int? storeID)
        {
            bool[] inList = new bool[999];
            int[] productQuantity = new int[999];
            int[] productID = new int[999];
            int i = 0;

            if (storeID == null)
            {
                return new HttpNotFoundResult();
            }

            Order order = new Order
            {
                guestID = User.Identity.GetUserId(),
                storeID = storeID
            };

            db.Order.Add(order);

            foreach (Product p in CartViewModel.shoppingCartList)
            {
                if (!inList[p.productID])
                {
                    inList[p.productID] = true;
                    productQuantity[p.productID] = 1;
                    productID[i] = p.productID;
                }
                else
                {
                    productQuantity[p.productID]++;
                }
                i++;
            }

            foreach (var item in productID)
            {
                if (item == 0)
                {
                    continue;
                }

                OrderRule o = new OrderRule
                {
                    orderID = order.orderID,
                    quantity = productQuantity[item],
                    productID = item
                };

                db.OrderRule.Add(o);
            }

            db.SaveChanges();

            return RedirectToAction("Index", "PDF", null);
        }

        [Authorize(Roles = "Admin,Klant,Medewerker")]
        public ActionResult Succes()
        {

            return View("~/Views/PDF/Index");
        }
    }
}

FlowerPower/Views/Confirmation/ChooseStore.cshtml
@model IEnumerable<FlowerPower.Models.Store>

@{
    ViewBag.Title = "ChooseStore";
    var stores = (SelectList)ViewBag.Stores;
}

<h2>ChooseStore</h2>

@Html.DropDownList("ddlStores", stores, "Selecteer een winkel", new { @class = "form-control" })

<div id="showOrderBtn">

</div>

@section Scripts {
    <script>
    $("#ddlStores").on("change", function () {
        $.ajax({
            url: "@Url.Action("GetOrderButton", "Confirmation")",
            method: "POST",
            data: {
                storeID: $("#ddlStores").val()
            },
            success: function (data) {
                $("#showOrderBtn").html(data);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                if (xhr.status == 404) {
                    $("#showOrderBtn").html("");
                }
            }
        });
    });
    </script>
    
    }

FlowerPower/Views/Confirmation/GetOrderButtonPartial.cshtml
<br />
<button id="orderBtn" type="submit" class="btn btn-success">
    <i class="fas fa-plus">Plaats bestelling</i>
</button>

<script>
    $("#orderBtn").click(function () {
        $.ajax({
                url: "@Url.Action("OnClickStoreButton", "Confirmation")",
                method: "POST",
                data: {
                    storeID: $("#ddlStores").val()
                },
                success: function (data) {
                    var link = '@Url.Action("Index", "PDF")';
                    window.location.href = link;
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    if (xhr.status == 404) {
                        return;
                    }
                }
        });
    });
</script>

FlowerPower/Views/Confirmation/Index.cshtml
@model IEnumerable<FlowerPower.Models.Product>

@{
    bool[] inList = new bool[999];
    int[] productQuantity = new int[999];
    int[] productID = new int[999];
    string[] productName = new string[999];
    int i = 0;
}

@foreach (var item in Model)
{
    if (!inList[item.productID])
    {
        inList[item.productID] = true;
        productQuantity[item.productID] = 1;
        productID[i] = item.productID;
        productName[item.productID] = item.productName;
    }
    else
    {
        productQuantity[item.productID]++;
    }
    i++;
}

<h2>Bevestiging</h2>

<div class="row">

    <div class="col-md-6">
        Product
    </div>
    <div class="col-md-6">
        Hoeveelheid
    </div>
</div>
<hr />

@foreach (var item in productID)
{
    if (item == 0)
    {
        continue;
    }
    <div class="row">

        <div class="col-md-6">
            @Html.DisplayFor(m => productName[item])
        </div>
        <div class="col-md-6">
            @Html.DisplayFor(m => productQuantity[item])
        </div>
    </div>
}

<div id="confirmTxt">
    Klopt dit?
</div>
<br />
<button id="confirmBtn" type="submit" class="btn btn-success">
    <i class="fas fa-plus">Ga verder</i>
</button>

@section Scripts{
    <script>
        $("#confirmBtn").click(function () {
            window.location.href = "@Url.Action("ChooseStore", "Confirmation")";
        });
    </script>
}