FlowerPower/Models/RolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Linq;
using System.Web.Mvc;
using FlowerPower.Controllers;
using FlowerPower.Models;

namespace FlowerPower
{
    public class RolesController : Controller
    {


        public ActionResult Index()
        {
            // Populate Dropdown Lists
            var context = new Models.ApplicationDbContext();

            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
            new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;

            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            ViewBag.Message = "";

            return View();
        }


        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {

            try
            {
                var context = new Models.ApplicationDbContext();
                context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.Message = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(string RoleName)
        {
            var context = new Models.ApplicationDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Roles/Edit/5
        public ActionResult Edit(string roleName)
        {
            var context = new Models.ApplicationDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                var context = new Models.ApplicationDbContext();
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //  Adding Roles to a user
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(string UserName, string RoleName)
        {
            var context = new Models.ApplicationDbContext();

            if (context == null)
            {
                throw new ArgumentNullException("context", "Context must not be null.");
            }

            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);
            userManager.AddToRole(user.Id, RoleName);


            ViewBag.Message = "Role created successfully !";

            // Repopulate Dropdown Lists
            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;
            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            return View("Index");
        }


        //Getting a List of Roles for a User
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                var context = new Models.ApplicationDbContext();
                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

                var userStore = new UserStore<ApplicationUser>(context);
                var userManager = new UserManager<ApplicationUser>(userStore);
                ViewBag.RolesForThisUser = userManager.GetRoles(user.Id);


                // Repopulate Dropdown Lists
                var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                ViewBag.Roles = rolelist;
                var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
                new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
                ViewBag.Users = userlist;
                ViewBag.Message = "Roles retrieved successfully !";
            }

            return View("Index");
        }

        //Deleting a User from A Role
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName)
        {
            var account = new AccountController();
            var context = new Models.ApplicationDbContext();
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);


            if (userManager.IsInRole(user.Id, RoleName))
            {
                userManager.RemoveFromRole(user.Id, RoleName);
                ViewBag.Message = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.Message = "This user doesn't belong to selected role.";
            }

            // Repopulate Dropdown Lists
            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;
            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            return View("Index");
        }

    }
}

FlowerPower/Controllers/RolesController.cs
using FlowerPower.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlowerPower.Controllers
{
    public class RolesController : Controller
    {

        private DB_A3D6D6_FlowerPowerJordyEntities db = new DB_A3D6D6_FlowerPowerJordyEntities();

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            // Populate Dropdown Lists
            var context = new ApplicationDbContext();

 

            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
            new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;

            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            ViewBag.Message = "";

            return View();
        }


        // GET: /Roles/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {

            try
            {
                var context = new Models.ApplicationDbContext();
                context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.Message = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string RoleName)
        {
            var context = new Models.ApplicationDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Roles/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string roleName)
        {
            var context = new Models.ApplicationDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                var context = new Models.ApplicationDbContext();
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //  Adding Roles to a user
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(string UserName, string RoleName)
        {
            var context = new Models.ApplicationDbContext();

            if (context == null)
            {
                throw new ArgumentNullException("context", "Context must not be null.");
            }

            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);
            userManager.AddToRole(user.Id, RoleName);

            Employee employee = null;

            if(RoleName.Equals("Medewerker"))
            {
                Employee employee2 = new Employee
                {
                    employeeID = user.Id,
                    employeeFirstName = db.Guest.Where(g => g.aspNetUserID == user.Id).First().firstName,
                    employeeLastName = db.Guest.Where(g => g.aspNetUserID == user.Id).First().lastName,
                    Active = true
                };

                db.Employee.Add(employee2);
                db.SaveChanges();

                employee = employee2;

                EmployeeAddModel.EmployeeID = employee.employeeID;
            }

            ViewBag.Message = "Role created successfully !";

            // Repopulate Dropdown Lists
            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;
            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            if (RoleName.Equals("Medewerker"))
            {
                IEnumerable<Store> stores = db.Store;
                SelectList storeList = new SelectList(stores, "storeID", "address");

                storeList.OrderBy(l => l.Value);

                ViewBag.Stores = storeList;

                return View("ChooseStore");
            }
            else
            {
                return View("Index");
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ChooseStore()
        {
            IEnumerable<Store> stores = db.Store;
            SelectList storeList = new SelectList(stores, "storeID", "address");

            storeList.OrderBy(l => l.Value);

            ViewBag.Stores = storeList;

            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult GetEmployeeButton(int? storeID)
        {
            Employee empl = db.Employee.Where(e => e.employeeID.Equals(EmployeeAddModel.EmployeeID)).First();

            if (storeID == null)
            {
                return new HttpNotFoundResult();
            }

            return PartialView("GetEmployeeButtonPartial", empl);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult OnClickEmployeeButton(int? storeID, string employeeID)
        {
            if (storeID == null)
            {
                return new HttpNotFoundResult();
            }

            Employee empl = db.Employee.Where(e => e.employeeID.Equals(employeeID)).First();
            empl.storeID = storeID;

            db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }


        //Getting a List of Roles for a User
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                var context = new Models.ApplicationDbContext();
                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

                var userStore = new UserStore<ApplicationUser>(context);
                var userManager = new UserManager<ApplicationUser>(userStore);
                ViewBag.RolesForThisUser = userManager.GetRoles(user.Id);


                // Repopulate Dropdown Lists
                var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                ViewBag.Roles = rolelist;
                var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
                new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
                ViewBag.Users = userlist;
                ViewBag.Message = "Roles retrieved successfully !";
            }

            return View("Index");
        }

        //Deleting a User from A Role
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName)
        {
            var account = new AccountController();
            var context = new Models.ApplicationDbContext();
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);


            if (userManager.IsInRole(user.Id, RoleName))
            {
                userManager.RemoveFromRole(user.Id, RoleName);
                ViewBag.Message = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.Message = "This user doesn't belong to selected role.";
            }

            // Repopulate Dropdown Lists
            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;
            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            return View("Index");
        }

    }
}

FlowerPower/Views/Roles/ChooseStore.cshtml
@model IEnumerable<FlowerPower.Models.Store>
@{
                ViewBag.Title = "ChooseStore";
                var stores = (SelectList)ViewBag.Stores;
}

<h2>ChooseStore</h2>

@Html.DropDownList("ddlStores", stores, "Selecteer een winkel", new { @class = "form-control" })

<div id="showEmployeeBtn">

</div>

@section Scripts {
    <script>
    $("#ddlStores").on("change", function () {
        $.ajax({
            url: "@Url.Action("GetEmployeeButton", "Roles")",
            method: "POST",
            data: {
                storeID: $("#ddlStores").val()
            },
            success: function (data) {
                $("#showEmployeeBtn").html(data);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                if (xhr.status == 404) {
                    $("#showEmployeeBtn").html("");
                }
            }
        });
    });
    </script>

}

FlowerPower/Views/Roles/Edit.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Edit Roles";
}

<h2>Edit Role</h2>

@Html.ActionLink("Return to Role Manager", "Index")
<hr />
@using (Html.BeginForm())
{
@Html.AntiForgeryToken()
@Html.ValidationSummary(true)
@Html.HiddenFor(model => model.Id)
<div>
    Role name
</div>
<p>
    @Html.TextBoxFor(model => model.Name)
</p>
<input type="submit" value="Save" />
}

FlowerPower/Views/Roles/GetEmployeeButtonPartial.cshtml
@model FlowerPower.Models.Employee

<br />
<button id="employeeBtn" type="submit" class="btn btn-success">
    <i class="fas fa-plus">Voeg medewerker toe</i>
</button>

<script>
    var empID = @Html.Raw(Json.Encode(Model.employeeID));
    console.log(empID);
    $("#employeeBtn").click(function () {
        $.ajax({
                url: "@Url.Action("OnClickEmployeeButton", "Roles")",
                method: "POST",
                data: {
                    storeID: $("#ddlStores").val(),
                    employeeID: empID
                },
                success: function (data) {
                    var link = '@Url.Action("Index", "Home")';
                    window.location.href = link;
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    if (xhr.status == 404) {
                        return;
                    }
                }
        });
    });
</script>

FlowerPower/Views/Roles/Index.cshtml
@{
    ViewBag.Title = "ManageUserRoles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row col-sm-12 col-lg-12 col-md-12">
    <h1>Rol beheer</h1>
    <br />
</div>

<div class="row col-sm-12 col-lg-12 col-md-12">


    <div class="col-sm-6 col-lg-6 col-md-6">
        <div class="panel panel-primary bg-primary">
            <div class="panel-heading rolesheader">
                <h4>Bestaande rollen</h4>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-hover col-sm-12 col-lg-12 col-md-12">
                    @foreach (var role in ViewBag.Roles)
                    {
                    <tr>
                        <td class="col-sm-6 col-lg-6 col-md-6">
                            <strong>@role.Text </strong>
                        </td>
                        <td class="col-sm-5 col-lg-5 col-md-5">
                            <span onclick="return confirm('Weet u zeker dat u het wilt verwijderen?')"><a href="/Roles/Delete?RoleName=@role.Text" class="addbutton">Verwijder</a></span>
                            @Html.ActionLink("Wijzigen", "Edit", new { roleName = @role.Text }, new { @class = "addbutton" })
                        </td>
                    </tr>
                    }
                </table>
            </div> <!-- End Panel Body-->
        </div> <!-- End Panel -->

        <div class="panel panel-primary bg-primary">
            <div class="panel-heading">
                <h4>Creeer een nieuwe rol</h4>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("Create", "Roles", new { @class = "form-horizontal" }))
                {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div>
                    Rol: @Html.TextBox("RoleName")
                    <input type="submit" value="Opslaan" class="btn-primary addbutton" />
                </div>
                }

            </div> <!--End Panel Body-->
        </div> <!--End Panel-->
    </div> <!--End First Column-->

    <div class="col-sm-6 col-lg-6 col-md-6">
        <div class="panel panel-primary bg-primary">
            <div class="panel-heading">
                <h4>Voeg een rol toe aan een gebruiker</h4>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("RoleAddToUser", "Roles"))
                {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <p>Gebruikersnaam: @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.Users, "Select ...")</p>
                <p>Rol: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select ...")</p>
                <p><input type="submit" value="Save" class="btn-primary addbutton" /></p>

                }
            </div> <!-- End Panel Body-->
        </div> <!-- End Panel -->


        <div class="panel panel-primary bg-primary">
            <div class="panel-heading">
                <h4>Benoem de rollen van een gebruiker</h4>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("GetRoles", "Roles"))
                {
                @Html.AntiForgeryToken()
                <p>
                    Gebruikersnaam: @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.Users, "Select ...")
                    <input type="submit" value="vraag op" class="btn-primary addbutton" />
                </p>
                }

                @if (ViewBag.RolesForThisUser != null)
                {
                <div class="alert-info">
                    <strong>Rollen voor deze gebruiker </strong>
                    <ol>
                        @foreach (string s in ViewBag.RolesForThisUser)
                            {
                        <li>@s</li>
                            }
                    </ol>
                </div>
                }
            </div> <!-- End Panel Body-->
        </div> <!-- End Panel -->

        <div class="panel panel-primary bg-primary">
            <div class="panel-heading">
                <h4>Verwijder rol van gebruiker</h4>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("DeleteRoleForUser", "Roles"))
                {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <p>User Name: @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.Users, "Select ...")</p>
                <p>Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select ...")</p>
                <p><input type="submit" value="Verwijder rol van gebruiker" class="btn-primary addbutton" /></p>

                }
            </div> <!-- End Panel Body-->
        </div> <!-- End Panel -->

    </div> <!--End Second Column-->

</div>  <!--Overall Page Wrapper-->

<div class="alert-info col-sm-12 col-lg-12 col-md-12">
    @ViewBag.Message
</div>