FlowerPower/Controllers/PDFController.cs
using FlowerPower.Models;
using Rotativa;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace FlowerPower.Controllers
{ 
    
    public class PDFController : Controller
    {
         DB_A3D6D6_FlowerPowerJordyEntities db = new DB_A3D6D6_FlowerPowerJordyEntities();
         public ActionResult PrintIndex()
         {
            CartViewModel.savedUserID = User.Identity.GetUserId();
            return new ActionAsPdf("Index") { FileName = "Factuur.pdf" };
         }

        public ActionResult Index()
        {
            string userID = "";
            if (CartViewModel.savedUserID != "")
            {
                userID = CartViewModel.savedUserID;
            }
            else
            {
                userID = User.Identity.GetUserId();
            }
            Order order = db.Order.OrderByDescending(o => o.orderID).Where(o => o.guestID == userID).First();

            ViewBag.Message = string.Format($"Hello {0} ASP.NET MVC!");

            return View(order);
        }

        public ActionResult TestViewWithModel(string id)
        {
            var model = db.Order;
            return new ViewAsPdf(model);
        }
    }
}

FlowerPower/Views/PDF/Index.cshtml
@model FlowerPower.Models.Order

@{
    ViewBag.Title = "Index";
    decimal totalPrice = 0;
}

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="invoice-title">
                <h2 class="pull-right">Factuur #@Model.orderID</h2>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-6">
                    <address>
                        <strong>Factuur bestemd voor:</strong><br>
                        @Model.Guest.firstName @Model.Guest.lastName<br>
                        @Model.Guest.address<br>
                        @Model.Guest.place, @Model.Guest.zipCode
                    </address>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <address>
                        <strong>datum:</strong><br>
                        @DateTime.Now.ToString("dddd, dd MMMM yyyy")<br><br>
                        <strong>U kunt uw bestelling binnen 1 werkdag ophalen.</strong>
                    </address>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Uw bestelling</strong></h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <td><strong>Product</strong></td>
                                    <td class="text-center"><strong>Hoeveelheid</strong></td>
                                    <td class="text-center"><strong>Prijs</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- foreach ($order->lineItems as $line) or some such thing here -->
                                @foreach (var orderrule in Model.OrderRule)
                                {
                                    var price = orderrule.Product.productPrice * orderrule.quantity;
                                    totalPrice += price;
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => orderrule.Product.productName)</td>
                                        <td class="text-center">@Html.DisplayFor(modelItem => orderrule.quantity)</td>
                                        <td class="text-center">@string.Format("{0:C}", price)</td>
                                    </tr>
                                }
                                <tr>
                                    <td class="no-line"></td>
                                    <td class="no-line"></td>
                                    <td class="no-line text-center"><strong>Totaal</strong></td>
                                    <td class="no-line text-right">@string.Format("{0:C}", totalPrice)</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @Html.ActionLink("Download factuur", "PrintIndex", "PDF", new { @class = "download-button" })
        </div>
    </div>
</div>